baseURL = 'https://moomew.github.io/myworld/'
languageCode = 'zh-cn'
title = '无名之诗' # 这里改成你想显示的名字
theme = 'PaperMod'
[outputs]
  home = ["HTML", "RSS", "JSON"]
[params]
  defaultTheme = "auto"
  ShowReadingTime = true

  # --- 1. 关掉 Profile Mode (加个 false 或者直接注释掉) ---
  [params.profileMode]
    enabled = false 

  # --- 2. 开启 Home Info (左侧文字介绍) ---
  [params.homeInfoParams]
    Title = "你好，这里是墨鱼 (:3)"
    Content = "这里用于存放个人作品集与世界观设定库。"
[[menu.main]]
  identifier = "search"
  name = "搜索"
  url = "/search/"
  weight = 10